# Generated by Django 4.2 on 2025-12-30 12:15

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('slack_user_id', models.CharField(blank=True, max_length=100)),
                ('slack_workspace_id', models.CharField(blank=True, max_length=100)),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('github_token', models.CharField(blank=True, max_length=200)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'agent_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('github_url', models.URLField()),
                ('github_branch', models.CharField(default='main', max_length=100)),
                ('clone_path', models.CharField(blank=True, max_length=500)),
                ('crs_workspace_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending Clone'), ('cloning', 'Cloning'), ('analyzing', 'Analyzing Structure'), ('questions_generated', 'Questions Generated'), ('questions_answered', 'Questions Answered'), ('crs_ready', 'CRS Ready'), ('crs_running', 'CRS Running'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('analysis', models.JSONField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('crs_status', models.CharField(default='not_started', max_length=50)),
                ('last_crs_run', models.DateTimeField(blank=True, null=True)),
                ('artifacts_count', models.IntegerField(default=0)),
                ('relationships_count', models.IntegerField(default=0)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('last_commit_sha', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_repositories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('initializing', 'Initializing'), ('analyzing', 'Analyzing Structure'), ('questions_pending', 'Questions Pending'), ('ready', 'Ready'), ('error', 'Error')], default='initializing', max_length=50)),
                ('workspace_path', models.CharField(blank=True, max_length=500)),
                ('system_spec_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_systems',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('planning', 'Planning'), ('awaiting_approval', 'Awaiting Approval'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('parsed_intent', models.JSONField(blank=True, null=True)),
                ('execution_plan', models.JSONField(blank=True, null=True)),
                ('impact_analysis', models.JSONField(blank=True, null=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('slack_message_ts', models.CharField(blank=True, max_length=100)),
                ('approved', models.BooleanField(null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('github_prs', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('affected_repos', models.ManyToManyField(related_name='affected_by_tasks', to='agent.repository')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agent.system')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepositoryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(max_length=50)),
                ('options', models.JSONField(blank=True, null=True)),
                ('answer', models.JSONField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='agent.repository')),
            ],
            options={
                'db_table': 'agent_repository_questions',
                'ordering': ['repository', 'order'],
            },
        ),
        migrations.AddField(
            model_name='repository',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='agent.system'),
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('pattern', 'Pattern Discovered'), ('preference', 'User Preference'), ('error', 'Error Encountered'), ('suggestion', 'Improvement Suggestion'), ('correction', 'User Correction')], max_length=50)),
                ('content', models.JSONField()),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learned_from_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_memories', to='agent.task')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='agent.system')),
            ],
            options={
                'db_table': 'agent_memories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_type', models.CharField(choices=[('architecture', 'System Architecture'), ('flow', 'Cross-Repo Flow'), ('contract', 'API Contract'), ('constraint', 'Business Rule'), ('pattern', 'Communication Pattern'), ('norm', 'Coding Convention')], max_length=50)),
                ('spec_id', models.CharField(max_length=200)),
                ('content', models.JSONField()),
                ('source', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=1.0)),
                ('spec_file_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='agent.system')),
            ],
            options={
                'db_table': 'agent_system_knowledge',
                'ordering': ['knowledge_type', 'spec_id'],
                'unique_together': {('system', 'knowledge_type', 'spec_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('system', 'name')},
        ),
    ]
