# Generated by Django 4.2 on 2025-12-30 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_reasoning_trace_and_docs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_type', models.CharField(choices=[('repository', 'Repository Chat'), ('planner', 'Planner Chat'), ('graph', 'Graph Exploration')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_provider', models.CharField(default='local', max_length=50)),
                ('repository', models.ForeignKey(blank=True, help_text='For repository-specific chats', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to='agent.repository')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to='agent.system')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='githuboauthconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('context_used', models.JSONField(blank=True, help_text='CRS artifacts/files used to generate response', null=True)),
                ('model_info', models.JSONField(blank=True, help_text='Model, provider, tokens used, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent.chatconversation')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_0a903c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['user', 'system', 'conversation_type'], name='chat_conver_user_id_8feaff_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['repository'], name='chat_conver_reposit_179508_idx'),
        ),
    ]
