# Generated by Django 4.2 on 2026-01-02 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_add_knowledge_fields'),
        ('agent', '0007_llm_request_log'),
    ]

    operations = [
    ]
