# Generated by Django 4.2 on 2026-01-02 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_merge_0007_add_knowledge_fields_0007_llm_request_log'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='llmrequestlog',
            name='llm_reques_user_id_fbd3bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='llmrequestlog',
            name='llm_reques_provide_1b6e95_idx',
        ),
        migrations.RemoveIndex(
            model_name='llmrequestlog',
            name='llm_reques_status_78c042_idx',
        ),
        migrations.AddField(
            model_name='llmrequestlog',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='llmrequestlog',
            name='llm_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='agent.llmmodel'),
        ),
        migrations.AddField(
            model_name='llmrequestlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='llmrequestlog',
            name='model_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='llmrequestlog',
            name='provider_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
