# Generated by Django 4.2 on 2026-01-02 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_remove_llmrequestlog_llm_reques_user_id_fbd3bb_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('session_type', models.CharField(choices=[('chat', 'Chat (RAG)'), ('task', 'Task (Autonomous)'), ('hybrid', 'Hybrid (Chat → Task)')], max_length=20)),
                ('intent_classified_as', models.CharField(blank=True, help_text="'CHAT' or 'TASK' from intent classifier", max_length=20, null=True)),
                ('user_request', models.TextField(help_text='Original user message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('plan', models.JSONField(blank=True, help_text='Agent execution plan (for tasks)', null=True)),
                ('steps', models.JSONField(default=list, help_text='Execution steps with timing and results')),
                ('final_answer', models.TextField(blank=True, null=True)),
                ('artifacts_used', models.JSONField(default=list, help_text='List of artifact IDs referenced')),
                ('tools_called', models.JSONField(default=list, help_text='Tools invoked during session')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('knowledge_context', models.JSONField(default=dict, help_text='Architecture style, domain, etc.')),
            ],
            options={
                'db_table': 'agent_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='repositoryreasoningtrace',
            name='repository',
        ),
        migrations.AlterModelOptions(
            name='agentmemory',
            options={'ordering': ['-importance', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='llmmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='repositoryquestion',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='systemdocumentation',
            options={'ordering': ['doc_type', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='systemknowledge',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='chatconversation',
            name='chat_conver_user_id_8feaff_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatconversation',
            name='chat_conver_reposit_179508_idx',
        ),
        migrations.AlterUniqueTogether(
            name='system',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='systemdocumentation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='systemknowledge',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='agentmemory',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='agentmemory',
            name='learned_from_task',
        ),
        migrations.RemoveField(
            model_name='llmrequestlog',
            name='error',
        ),
        migrations.RemoveField(
            model_name='llmrequestlog',
            name='llm_model',
        ),
        migrations.RemoveField(
            model_name='llmrequestlog',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='llmrequestlog',
            name='model_id',
        ),
        migrations.RemoveField(
            model_name='llmrequestlog',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='llmrequestlog',
            name='provider_type',
        ),
        migrations.RemoveField(
            model_name='llmrequestlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='artifacts_count',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='crs_status',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='crs_workspace_path',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='knowledge_docs_count',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='knowledge_last_extracted',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='knowledge_status',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='last_crs_run',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='last_synced',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='relationships_count',
        ),
        migrations.RemoveField(
            model_name='task',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='changes',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='execution_plan',
        ),
        migrations.RemoveField(
            model_name='task',
            name='github_prs',
        ),
        migrations.RemoveField(
            model_name='task',
            name='impact_analysis',
        ),
        migrations.RemoveField(
            model_name='task',
            name='parsed_intent',
        ),
        migrations.RemoveField(
            model_name='task',
            name='requires_approval',
        ),
        migrations.RemoveField(
            model_name='task',
            name='slack_message_ts',
        ),
        migrations.RemoveField(
            model_name='task',
            name='started_at',
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='importance',
            field=models.IntegerField(default=5, help_text='1-10 scale'),
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='local_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='system',
            name='knowledge_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemdocumentation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='systemdocumentation',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='systemknowledge',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemknowledge',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='systemknowledge',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='plan',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='task',
            name='result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.CharField(db_index=True, default='e422b91f-e78b-11f0-82d8-94f168a3f8bf', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agentmemory',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='agentmemory',
            name='memory_type',
            field=models.CharField(choices=[('fact', 'Fact'), ('decision', 'Decision'), ('preference', 'Preference'), ('context', 'Context')], max_length=100),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='conversation_type',
            field=models.CharField(choices=[('repository', 'Repository Chat'), ('planner', 'System Planner'), ('graph', 'Graph Explorer')], default='repository', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='llm_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='agent.llmmodel'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='model_provider',
            field=models.CharField(default='ollama', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='agent.repository'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='agent.system'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='title',
            field=models.CharField(default='New Conversation', max_length=200),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='llmrequestlog',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_requests', to='agent.chatconversation'),
        ),
        migrations.AlterField(
            model_name='llmrequestlog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llmrequestlog',
            name='latency_ms',
            field=models.IntegerField(help_text='Response time in milliseconds'),
        ),
        migrations.AlterField(
            model_name='llmrequestlog',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.llmmodel'),
        ),
        migrations.AlterField(
            model_name='llmrequestlog',
            name='request_type',
            field=models.CharField(choices=[('completion', 'Completion'), ('stream', 'Stream'), ('embedding', 'Embedding')], max_length=50),
        ),
        migrations.AlterField(
            model_name='llmrequestlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], max_length=20),
        ),
        migrations.AlterField(
            model_name='repository',
            name='analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='repository',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='last_commit_sha',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='repository',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('questions_generated', 'Questions Generated'), ('questions_answered', 'Questions Answered'), ('crs_running', 'CRS Running'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='repositoryquestion',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='repositoryquestion',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='repositoryquestion',
            name='question_type',
            field=models.CharField(choices=[('yes_no', 'Yes/No'), ('text', 'Text'), ('multiple_choice', 'Multiple Choice'), ('list', 'List')], max_length=50),
        ),
        migrations.AlterField(
            model_name='repositoryquestion',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='system',
            name='intent_constraints',
            field=models.JSONField(blank=True, default=dict, help_text='User-defined intent summary and constraints for this system'),
        ),
        migrations.AlterField(
            model_name='system',
            name='status',
            field=models.CharField(choices=[('initializing', 'Initializing'), ('ready', 'Ready'), ('error', 'Error')], default='initializing', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemdocumentation',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='systemdocumentation',
            name='doc_type',
            field=models.CharField(choices=[('overview', 'Overview'), ('architecture', 'Architecture'), ('api', 'API Reference'), ('guide', 'Guide')], max_length=100),
        ),
        migrations.AlterField(
            model_name='systemknowledge',
            name='knowledge_type',
            field=models.CharField(choices=[('pattern', 'Pattern'), ('convention', 'Convention'), ('architecture', 'Architecture'), ('dependency', 'Dependency')], max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='affected_repos',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='agent.repository'),
        ),
        migrations.AlterField(
            model_name='task',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('planning', 'Planning'), ('awaiting_approval', 'Awaiting Approval'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='repositoryquestion',
            unique_together={('repository', 'question_key')},
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['user', '-updated_at'], name='chat_conver_user_id_9d8b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['repository', '-updated_at'], name='chat_conver_reposit_be217b_idx'),
        ),
        migrations.AddIndex(
            model_name='llmrequestlog',
            index=models.Index(fields=['conversation', '-created_at'], name='llm_request_convers_8455f2_idx'),
        ),
        migrations.AddIndex(
            model_name='llmrequestlog',
            index=models.Index(fields=['status', '-created_at'], name='llm_request_status_8d7cdf_idx'),
        ),
        migrations.AlterModelTable(
            name='repository',
            table='repositories',
        ),
        migrations.AlterModelTable(
            name='repositoryquestion',
            table='repository_questions',
        ),
        migrations.AlterModelTable(
            name='system',
            table='systems',
        ),
        migrations.AlterModelTable(
            name='systemdocumentation',
            table='system_documentation',
        ),
        migrations.AlterModelTable(
            name='systemknowledge',
            table='system_knowledge',
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
        migrations.DeleteModel(
            name='RepositoryReasoningTrace',
        ),
        migrations.AddField(
            model_name='agentsession',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='agent.chatconversation'),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='llm_model_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to='agent.llmmodel'),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='agent.repository'),
        ),
        migrations.RemoveField(
            model_name='system',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='system',
            name='system_spec_path',
        ),
        migrations.RemoveField(
            model_name='system',
            name='workspace_path',
        ),
        migrations.RemoveField(
            model_name='systemknowledge',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='systemknowledge',
            name='content',
        ),
        migrations.RemoveField(
            model_name='systemknowledge',
            name='source',
        ),
        migrations.RemoveField(
            model_name='systemknowledge',
            name='spec_file_path',
        ),
        migrations.RemoveField(
            model_name='systemknowledge',
            name='spec_id',
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['repository', '-created_at'], name='agent_sessi_reposit_4bca54_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['session_type', 'status'], name='agent_sessi_session_81e4e3_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['conversation', '-created_at'], name='agent_sessi_convers_b3dbe2_idx'),
        ),
    ]
