# Generated by Django 4.2 on 2026-01-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_alter_llmrequestlog_latency_ms_alter_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(db_index=True, default='07ae7280-e792-11f0-8c27-94f168a3f8bf', max_length=100, unique=True),
        ),
    ]
