# Generated by Django 4.2 on 2026-01-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0013_merge_0012_alter_task_task_id_0012_benchmark_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('system_prompt_template', models.TextField(help_text='System prompt template. Use {{tools}} and {{context}} placeholders.')),
                ('temperature', models.FloatField(default=0.7)),
                ('knowledge_scope', models.CharField(choices=[('system', 'Full System Context'), ('repository', 'Repository Only'), ('none', 'No RAG / Isolation')], default='system', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToolDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique tools identifier (e.g., LIST_ARTIFACTS)', max_length=100, unique=True)),
                ('category', models.CharField(default='general', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tool_definitions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='benchmarkrun',
            new_name='benchmark_r_user_id_bd8c76_idx',
            old_name='benchmark_runs_user_id_b6757d_idx',
        ),
        migrations.RenameIndex(
            model_name='benchmarkrun',
            new_name='benchmark_r_status_6cb715_idx',
            old_name='benchmark_runs_status_6bf5ad_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(db_index=True, default='550decc4-e971-11f0-a70f-94f168a3f8bf', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='default_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_profiles', to='agent.llmmodel'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='agent_profiles', to='agent.tooldefinition'),
        ),
    ]
