# Generated by Django 4.2 on 2026-01-04 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0014_agentprofile_tooldefinition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='repository',
            field=models.ForeignKey(blank=True, help_text="Expected repository context if scope is 'repository'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_profiles', to='agent.repository'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(db_index=True, default='dcf0544e-e975-11f0-874e-94f168a3f8bf', max_length=100, unique=True),
        ),
    ]
