# Generated by Django 4.2 on 2026-01-04 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0015_agentprofile_repository_alter_task_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('base_url', models.URLField()),
                ('auth_type', models.CharField(max_length=50)),
                ('auth_config', models.JSONField(default=dict)),
                ('api_spec_url', models.URLField(blank=True, null=True)),
                ('api_spec_content', models.JSONField(blank=True, null=True)),
                ('api_docs_url', models.URLField(blank=True, null=True)),
                ('knowledge_context', models.TextField(blank=True)),
                ('examples', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('total_actions', models.IntegerField(default=0)),
                ('enabled_actions', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'remote_services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='repository',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(db_index=True, default='88f90b61-e978-11f0-87eb-94f168a3f8bf', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ServiceKnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('api_guide', 'API Guide'), ('example', 'Code Example'), ('tutorial', 'Tutorial'), ('faq', 'FAQ'), ('troubleshooting', 'Troubleshooting'), ('changelog', 'Changelog'), ('best_practice', 'Best Practice')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('source_url', models.URLField(blank=True, null=True)),
                ('embedding_vector', models.JSONField(blank=True, null=True)),
                ('relevance_score', models.FloatField(default=1.0)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entries', to='agent.remoteservice')),
            ],
            options={
                'verbose_name_plural': 'Service knowledge entries',
                'db_table': 'service_knowledge_entries',
                'ordering': ['-relevance_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('action_group', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('endpoint_path', models.CharField(max_length=500)),
                ('http_method', models.CharField(default='POST', max_length=10)),
                ('parameters', models.JSONField(default=list)),
                ('request_body_schema', models.JSONField(blank=True, null=True)),
                ('response_schema', models.JSONField(blank=True, null=True)),
                ('execution_pattern', models.CharField(choices=[('simple', 'Simple Request-Response'), ('async_polling', 'Async with Polling'), ('webhook', 'Webhook Callback'), ('multi_step', 'Multi-step Workflow'), ('streaming', 'Streaming Response')], default='simple', max_length=50)),
                ('polling_config', models.JSONField(blank=True, null=True)),
                ('webhook_config', models.JSONField(blank=True, null=True)),
                ('tool_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('execution_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('average_execution_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='agent.remoteservice')),
            ],
            options={
                'db_table': 'service_actions',
                'ordering': ['service', 'action_group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RemoteToolJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=255)),
                ('internal_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('input_parameters', models.JSONField(default=dict)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('poll_attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='agent.serviceaction')),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'remote_tool_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='serviceknowledgeentry',
            index=models.Index(fields=['service', 'entry_type'], name='service_kno_service_6d5bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceknowledgeentry',
            index=models.Index(fields=['service', '-relevance_score'], name='service_kno_service_e7c893_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceaction',
            index=models.Index(fields=['service', 'action_group'], name='service_act_service_e4714b_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceaction',
            index=models.Index(fields=['tool_name'], name='service_act_tool_na_8e7559_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceaction',
            index=models.Index(fields=['service', 'enabled'], name='service_act_service_afab2f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceaction',
            unique_together={('service', 'name')},
        ),
        migrations.AddIndex(
            model_name='remotetooljob',
            index=models.Index(fields=['job_id'], name='remote_tool_job_id_9b98b2_idx'),
        ),
        migrations.AddIndex(
            model_name='remotetooljob',
            index=models.Index(fields=['internal_id'], name='remote_tool_interna_89cf9b_idx'),
        ),
        migrations.AddIndex(
            model_name='remotetooljob',
            index=models.Index(fields=['user', '-created_at'], name='remote_tool_user_id_48419b_idx'),
        ),
        migrations.AddIndex(
            model_name='remotetooljob',
            index=models.Index(fields=['status', '-created_at'], name='remote_tool_status_8c9956_idx'),
        ),
        migrations.AddIndex(
            model_name='remoteservice',
            index=models.Index(fields=['created_by', 'enabled'], name='remote_serv_created_2a1221_idx'),
        ),
        migrations.AddIndex(
            model_name='remoteservice',
            index=models.Index(fields=['slug'], name='remote_serv_slug_99e9a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='remoteservice',
            unique_together={('created_by', 'slug')},
        ),
    ]
