# Generated by Django 4.2 on 2026-01-05 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0016_remoteservice_remove_agentprofile_repository_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteservice',
            name='discovery_method',
            field=models.CharField(choices=[('openapi', 'OpenAPI/Swagger Spec'), ('postman', 'Postman Collection'), ('graphql', 'GraphQL Schema'), ('html_docs', 'HTML Documentation'), ('manual', 'Manual Entry')], default='openapi', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(db_index=True, default='148d1790-ea36-11f0-88f2-94f168a3f8bf', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ContextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='context_files/%Y/%m/%d/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_files', to='agent.chatconversation')),
            ],
            options={
                'db_table': 'context_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
