# Generated by Django 4.2 on 2026-01-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0017_remoteservice_discovery_method_alter_task_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(db_index=True, default='5b615142-ea3a-11f0-b512-94f168a3f8bf', max_length=100, unique=True),
        ),
    ]
