# Generated by Django 4.2 on 2026-01-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0018_chatconversation_metadata_alter_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(db_index=True, default='a59585b8-ea3b-11f0-b2d9-94f168a3f8bf', max_length=100, unique=True),
        ),
    ]
