# Generated by Django 4.2 on 2026-01-05 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0019_alter_task_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextfile',
            name='agent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_files', to='agent.agentprofile'),
        ),
        migrations.AddField(
            model_name='contextfile',
            name='analysis',
            field=models.TextField(blank=True, help_text='AI Analysis/Summary of the file'),
        ),
        migrations.AlterField(
            model_name='contextfile',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='context_files', to='agent.chatconversation'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(db_index=True, default='21efa5b4-ea3f-11f0-93d0-94f168a3f8bf', max_length=100, unique=True),
        ),
    ]
