# Generated by Django 4.2 on 2026-01-05 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0020_contextfile_agent_profile_contextfile_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsession',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='agent.repository'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(db_index=True, default='e5e25c04-ea3f-11f0-aa67-94f168a3f8bf', max_length=100, unique=True),
        ),
    ]
