# Generated by Django 4.2 on 2026-01-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0021_alter_agentsession_repository_alter_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(db_index=True, default='db7c3a14-ea55-11f0-8e6e-94f168a3f8bf', max_length=100, unique=True),
        ),
    ]
